import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import { inter } from "@/fonts/fonts";
import "@/styles/main.scss";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <section className="home-page">{children}</section>
        <Footer />
      </body>
    </html>
  );
}
