name: Deployment workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  avoid_redundancy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: 20
      - name: Cancel Previus Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with: 
          access_token: ${{ github.token  }}

  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ['install', 'lint', 'build']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: 20
      - name: Install dependencies
        run: npm ci 
      - name: Run job
        run: npm run ${{ matrix.job }}
    needs: avoid_reduncy 
      